# Generated by Django 4.2.9 on 2024-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_department_team_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(default=None, null=True, to='api.role'),
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ManyToManyField(default=None, null=True, to='api.department'),
        ),
    ]
