# Generated by Django 4.2.9 on 2024-06-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_role_remove_team_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(blank=True, default=None, to='api.role'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ManyToManyField(blank=True, default=None, to='api.department'),
        ),
    ]
