# Generated by Django 4.2.9 on 2024-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_profile_course_remove_profile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
