# Generated by Django 4.2.9 on 2024-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(blank=True, default=None, to='api.team'),
        ),
    ]
