# Generated by Django 4.2.9 on 2024-08-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_team_members_profile_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='department',
            new_name='departments',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
