# Generated by Django 4.2.9 on 2024-08-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
