# Generated by Django 4.2.9 on 2024-09-10 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '__first__'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Assign', 'Assign'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Escalated', 'Escalated'), ('Rejected', 'Rejected')], default='Open', max_length=20, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalation_level', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accepted', models.ManyToManyField(blank=True, default=None, related_name='accepted', to='api.profile')),
                ('assigned_to', models.ManyToManyField(blank=True, default=None, related_name='assigned_incidents', to='api.profile')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.building')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.classroom')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('forfeited', models.BooleanField(default=False)),
                ('forfeited_reason', models.TextField()),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.incident')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_notes', models.TextField()),
                ('resolution_date', models.DateTimeField(auto_now_add=True)),
                ('resolution_time', models.DurationField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='incident.incident')),
                ('teams', models.ManyToManyField(blank=True, default=None, to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.ManyToManyField(blank=True, default=None, to='incident.incidenttype'),
        ),
        migrations.AddField(
            model_name='incident',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='incident',
            name='teams',
            field=models.ManyToManyField(blank=True, default=None, to='api.team'),
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EscalationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_type', models.CharField(choices=[('Functional', 'Functional'), ('Hierarchical', 'Hierarchical')], max_length=50)),
                ('previous_level', models.IntegerField()),
                ('new_level', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('escalated_to', models.ManyToManyField(blank=True, default=None, related_name='escalated_to', to='api.profile')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to='incident.incident')),
            ],
        ),
    ]
