# Generated by Django 4.2.9 on 2024-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='profile',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='task',
            name='forfeited_reason',
            field=models.TextField(blank=True),
        ),
    ]
