# Generated by Django 4.2.9 on 2024-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_course_alter_profile_level_and_more'),
        ('incident', '0002_incident_building_incident_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('UnderReview', 'Under Review'), ('Assigning', 'Assigning'), ('Resolution', 'Resolution'), ('Close', 'Close')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='incident',
            name='team',
        ),
        migrations.AddField(
            model_name='incident',
            name='team',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='api.team'),
        ),
    ]
