# Generated by Django 4.2.9 on 2024-06-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_course_alter_profile_level_and_more'),
        ('incident', '0003_alter_incident_status_remove_incident_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='team',
            field=models.ManyToManyField(blank=True, default=None, to='api.team'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
