# Generated by Django 4.2.9 on 2024-09-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('incident', '0004_steps_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='attendees',
            field=models.ManyToManyField(blank=True, default=None, to='api.profile'),
        ),
    ]
