# Generated by Django 4.2.9 on 2024-09-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('incident', '0005_alter_steps_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
