# Generated by Django 4.2.9 on 2024-09-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_workflow_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='emmergency',
            field=models.BooleanField(default=False),
        ),
    ]
