# Generated by Django 4.2.9 on 2024-06-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_incident_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
