# Generated by Django 4.2.9 on 2024-06-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_course_alter_profile_level_and_more'),
        ('incident', '0007_incident_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='team',
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_notes', models.TextField()),
                ('resolution_date', models.DateTimeField(auto_now_add=True)),
                ('resolution_time', models.DurationField()),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='incident.incident')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_type', models.CharField(choices=[('Functional', 'Functional'), ('Hierarchical', 'Hierarchical')], max_length=50)),
                ('previous_level', models.IntegerField()),
                ('new_level', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to='incident.incident')),
            ],
        ),
    ]
