# Generated by Django 4.2.9 on 2024-09-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0009_steps_timestamp_workflow_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.incidenttype'),
        ),
    ]
