# Generated by Django 4.2.9 on 2024-06-12 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_course_alter_profile_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident', '0009_incidenttype_incident_escalation_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
