# Generated by Django 4.2.9 on 2024-07-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_role_alter_team_department'),
        ('incident', '0010_incident_profile_alter_incident_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='teams',
            field=models.ManyToManyField(blank=True, default=None, to='api.team'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Escalated', 'Escalated'), ('Rejected', 'Rejected')], default='Open', max_length=20, null=True),
        ),
    ]
