# Generated by Django 4.2.9 on 2024-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0010_steps_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
