# Generated by Django 4.2.9 on 2024-08-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0011_incident_teams_alter_incident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
