# Generated by Django 4.2.9 on 2024-09-14 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('incident', '0011_steps_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='attendees',
        ),
        migrations.AlterField(
            model_name='steps',
            name='step',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='attendees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
