# Generated by Django 4.2.9 on 2024-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0013_alter_incident_latitude_alter_incident_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
