# Generated by Django 4.2.9 on 2024-09-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0014_rename_workflow_incident_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='workFlow',
            new_name='workflow',
        ),
    ]
