# Generated by Django 4.2.9 on 2024-08-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_roles_profile_role_and_more'),
        ('incident', '0014_alter_incident_latitude_alter_incident_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, default=None, related_name='assigned_incidents', to='api.profile'),
        ),
    ]
