# Generated by Django 4.2.9 on 2024-09-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_rename_workflow_incident_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='step',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
