# Generated by Django 4.2.9 on 2024-08-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_incident_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Assign', 'Assign'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Escalated', 'Escalated'), ('Rejected', 'Rejected')], default='Open', max_length=20, null=True),
        ),
    ]
