# Generated by Django 4.2.9 on 2024-08-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0017_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.incident'),
        ),
    ]
