# Generated by Django 4.2.9 on 2024-08-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_staff'),
        ('incident', '0018_task_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='incident',
        ),
        migrations.AddField(
            model_name='incident',
            name='accepted',
            field=models.ManyToManyField(blank=True, default=None, related_name='accepted', to='api.profile'),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolutions',
            field=models.ManyToManyField(blank=True, default=None, to='incident.resolution'),
        ),
    ]
