# Generated by Django 4.2.9 on 2024-08-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0019_remove_resolution_incident_incident_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='resolutions',
        ),
        migrations.AddField(
            model_name='resolution',
            name='incident',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='incident.incident'),
            preserve_default=False,
        ),
    ]
