# Generated by Django 4.2.9 on 2024-08-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0020_remove_incident_resolutions_resolution_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolution',
            old_name='resolved_by',
            new_name='teams',
        ),
    ]
