# Generated by Django 4.2.9 on 2024-06-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='building',
        ),
        migrations.AddField(
            model_name='building',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.faculty'),
            preserve_default=False,
        ),
    ]
