# Generated by Django 4.2.9 on 2024-06-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_specific_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='building',
        ),
        migrations.RemoveField(
            model_name='location',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='location',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='location',
            name='floor',
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.building')),
            ],
        ),
    ]
