# Generated by Django 4.2.9 on 2024-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_building_remove_location_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
